name: Node Continuous Integration

on: 
  push:

jobs:
  build-node:
    name: Build and run Node project
    runs-on: ubuntu-latest

    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v3

      - name: Check Node version
        run: node --version

      - name: Check NPM version
        run: npm --version

      - name: Install NPM packages
        run: npm install

      - name: Run Node Application
        run: node server/app.js
